[package]
name = "program-runtime"
version = "1.9.29"
description = "program runtime"
authors = [""]
repository = ""
license = "Apache-2.0"
homepage = ""
documentation = ""
edition = "2021"

[dependencies]
base64 = "0.13"
bincode = "1.3.3"
itertools =  "0.10.1"
libc = "0.2.101"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = { version = "1.0.129", features = ["derive", "rc"] }
frozen-abi = { path = "../frozen-abi", version = "=1.9.29" }
frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.29" }
logger = { path = "../logger", version = "=1.9.29" }
measure = { path = "../measure", version = "=1.9.29" }
sdk = { path = "../sdk", version = "=1.9.29" }
evm-state = { path = "../evm-utils/evm-state" }
thiserror = "1.0"

[lib]
crate-type = ["lib"]
name = "program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
